services:
  - type: web
    name: lcs-api
    plan: free
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && mkdir -p build && cp -r ../frontend/build/* ./build/ && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    dir: backend

